// Research Hub — generated by research-visualizer v8.14.1
import React, { useState } from 'react';
import { LayoutDashboard, Search, DollarSign, Shield, MapPin, Heart, Rocket, BookOpen, ChevronRight } from 'lucide-react';

import Overview from './components/Overview';
import ActivityExplorer from './components/ActivityExplorer';
import CostComparison from './components/CostComparison';
import BarrierToEntry from './components/BarrierToEntry';
import LocationGuide from './components/LocationGuide';
import HealthFitness from './components/HealthFitness';
import GettingStarted from './components/GettingStarted';
import Sources from './components/Sources';

const SECTIONS = [
  { key: 'overview', label: 'Overview', icon: LayoutDashboard, component: Overview },
  { key: 'activity-explorer', label: 'Activity Explorer', icon: Search, component: ActivityExplorer },
  { key: 'cost-comparison', label: 'Cost Comparison', icon: DollarSign, component: CostComparison },
  { key: 'barrier-to-entry', label: 'Barrier To Entry', icon: Shield, component: BarrierToEntry },
  { key: 'location-guide', label: 'Location Guide', icon: MapPin, component: LocationGuide },
  { key: 'health-fitness', label: 'Health & Fitness', icon: Heart, component: HealthFitness },
  { key: 'getting-started', label: 'Getting Started', icon: Rocket, component: GettingStarted },
  { key: 'sources', label: 'Sources', icon: BookOpen, component: Sources },
];

export default function App() {
  const [activeSection, setActiveSection] = useState(SECTIONS[0].key);
  const ActiveComponent = SECTIONS.find(s => s.key === activeSection)?.component || SECTIONS[0].component;

  return (
    <div className="flex h-full bg-gray-950 text-white">
      {/* Sidebar */}
      <nav className="w-56 flex-shrink-0 border-r border-gray-800 bg-gray-950/50 overflow-y-auto">
        <div className="p-4">
          <h1 className="text-base font-bold text-white mb-0.5">Coquitlam & Burnaby Active Lifestyle Guide</h1>
          <p className="text-xs text-gray-400 mb-4">18 Fun Activities & Sports for Adults in Their 40s</p>
          <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-3">Sections</h2>
          <ul className="space-y-1">
            {SECTIONS.map(s => {
              const Icon = s.icon;
              return (
                <li key={s.key}>
                  <button
                    onClick={() => setActiveSection(s.key)}
                    className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-sm transition-colors cursor-pointer ${
                      activeSection === s.key
                        ? 'bg-teal-500/20 text-teal-300'
                        : 'text-gray-400 hover:text-white hover:bg-gray-800/50'
                    }`}
                  >
                    <Icon className="w-4 h-4" />
                    {s.label}
                    {activeSection === s.key && <ChevronRight className="w-3 h-3 ml-auto" />}
                  </button>
                </li>
              );
            })}
          </ul>
        </div>
      </nav>

      {/* Main content */}
      <main className="flex-1 overflow-y-auto">
        <div className="max-w-5xl mx-auto px-6 py-8">
          <ActiveComponent />
        </div>
      </main>
    </div>
  );
}
