import { lazy } from 'react';

export const projectRegistry = [
  {
    slug: 'coquitlam-active-lifestyle',
    title: 'Coquitlam & Burnaby Active Lifestyle Guide',
    subtitle: '18 Fun Activities & Sports for Adults in Their 40s',
    query: 'research activities and sports that i can do in my fourties here in coquitlam and burnaby british columbia. include barrier to entry, costs, locations. how to get started at the location.',
    lens: 'standard',
    icon: 'Activity',
    accentColor: 'teal',
    visibility: 'personal',
    createdAt: '2026-03-16T21:44:53.641Z',
  },
  {
    slug: 'satisfactory-optimized-builds',
    title: 'Satisfactory Optimized Builds',
    subtitle: 'Deep Dive into Factory Optimization',
    query: 'deep dive research into the most optimized satisfactory builds',
    lens: 'standard',
    icon: 'Factory',
    accentColor: 'orange',
    visibility: 'personal',
    createdAt: '2026-02-10T21:26:00Z',
    updatedAt: '2026-02-10T21:26:00Z',
  },
  {
    slug: 'japan-dmc-luxury-travel',
    title: 'Japan DMC & Luxury Travel Intelligence',
    subtitle: 'Destination Management Companies for Japan Luxury Tourism',
    query: 'deep dive research into Destination Management Companies (DMC) for Japan, Japan tourism, japan luxe tourism for a travel specialist agent',
    lens: 'standard',
    icon: 'Plane',
    accentColor: 'rose',
    visibility: 'personal',
    createdAt: '2026-02-10T22:23:00Z',
    updatedAt: '2026-02-10T22:23:00Z',
  },
  {
    slug: 'bar-raptors-4p-guide',
    title: 'BAR Raptors 4P Guide',
    subtitle: 'Optimized 4-Player Team Build vs Raptors — Hardest Difficulty',
    query: 'research beyond all reason, specifically for a 4 person player team going up against the AI raptors on the hardest difficulty setting, what is the optimized build for these four players to do',
    lens: 'standard',
    icon: 'Shield',
    accentColor: 'red',
    visibility: 'personal',
    createdAt: '2026-02-10T22:23:00Z',
    updatedAt: '2026-02-10T22:23:00Z',
  },
  {
    slug: 'jeep-rubicon-overlanding',
    title: 'Jeep Rubicon Overlanding Setup',
    subtitle: 'Complete Tent Camping & RTT Comparison for Overlanding',
    query: 'deep dive research into the best jeep rubicon tent camping setup for overlanding',
    lens: 'product',
    icon: 'Tent',
    accentColor: 'emerald',
    visibility: 'personal',
    createdAt: '2026-02-10T22:45:00Z',
    updatedAt: '2026-02-10T22:45:00Z',
  },
  {
    slug: 'japan-vegan-gf-guide',
    title: 'Japan Vegan & Gluten-Free Guide',
    subtitle: 'Interactive Restaurant Map, Reviews & Food Safety for Dietary-Restricted Travelers',
    query: 'deep dive research into vegan friendly restaurants in japan with interactive map, gluten free options, reviews, ratings',
    lens: 'standard',
    icon: 'Leaf',
    accentColor: 'green',
    visibility: 'personal',
    createdAt: '2026-02-11T16:30:00Z',
    updatedAt: '2026-02-11T16:30:00Z',
  },
  {
    slug: 'japanese-learning-dashboard',
    title: 'Japanese Learning Dashboard',
    subtitle: 'Beginner to Advanced — Grammar, Vocab, Kana, Verbs & Interactive Translator',
    query: 'build me a japanese learning dashboard that goes from beginner to advanced, grammar, vocab, hiragana, katakana, romaji, structured courses, verb reference, and a sentence translator',
    lens: 'standard',
    icon: 'GraduationCap',
    accentColor: 'rose',
    visibility: 'personal',
    createdAt: '2026-02-13T18:09:00Z',
    updatedAt: '2026-02-13T18:09:00Z',
  },
  {
    slug: 'global-travel-guide',
    title: 'Global Travel Guide',
    subtitle: 'Activities, Food, Entertainment, Hotels, Attractions & Budget Intelligence',
    query: 'build a global travel guide to activities food entertainment as well as hotel ratings, best places to visit, best attractions, everything that vacationers would want to know',
    lens: 'standard',
    icon: 'Globe',
    accentColor: 'cyan',
    visibility: 'personal',
    createdAt: '2026-02-14T20:37:00Z',
    updatedAt: '2026-02-14T20:37:00Z',
  },
];

export const projectComponents = {
  'bar-raptors-4p-guide': lazy(() => import('./bar-raptors-4p-guide/App')),
  'coquitlam-active-lifestyle': lazy(() => import('./coquitlam-active-lifestyle/App')),
  'global-travel-guide': lazy(() => import('./global-travel-guide/App')),
  'japan-dmc-luxury-travel': lazy(() => import('./japan-dmc-luxury-travel/App')),
  'japan-vegan-gf-guide': lazy(() => import('./japan-vegan-gf-guide/App')),
  'japanese-learning-dashboard': lazy(() => import('./japanese-learning-dashboard/App')),
  'jeep-rubicon-overlanding': lazy(() => import('./jeep-rubicon-overlanding/App')),
  'satisfactory-optimized-builds': lazy(() => import('./satisfactory-optimized-builds/App')),
};
